import re
from pathlib import Path

files_to_merge = [
    "app/config.py",
    "app/utils.py",
    "app/enhance.py",
    "app/detector.py",
    "app/tracker.py",
    "app/blur.py",
    "app/image_processor.py",
    "app/video_processor.py",
    "main.py"
]

out_lines = []
out_lines.append("# " + "="*70)
out_lines.append("# Face Blur Pipeline - Standalone Script")
out_lines.append("# " + "="*70)
out_lines.append("# This file was auto-generated by concatenating the project modules.")
out_lines.append("")

for f in files_to_merge:
    content = Path(f).read_text(encoding="utf-8")
    
    out_lines.append(f"\n# {'='*70}\n# --- FILE: {f} ---\n# {'='*70}\n")
    
    for line in content.split('\n'):
        # Remove any internal local imports regardless of indentation
        if re.match(r'^\s*from app\..* import ', line):
            continue
        if re.match(r'^\s*import app\.', line):
            continue
            
        # Optional: remove path manipulation logic in main.py
        if "if str(PROJECT_ROOT) not in sys.path:" in line:
            continue
        if "sys.path.insert" in line and "PROJECT_ROOT" in line:
            continue
            
        out_lines.append(line)

with open("script.py", "w", encoding="utf-8") as out:
    out.write("\n".join(out_lines))

print("Successfully created script.py!")
