# ======================================================================
# Face Blur Pipeline - Standalone Script
# ======================================================================
# This file was auto-generated by concatenating the project modules.


# ======================================================================
# --- FILE: app/config.py ---
# ======================================================================

"""
config.py — Central Configuration for Face Blur Pipeline
=========================================================

All tunable parameters live here. Other modules import from this file
so that every knob is in one place.  Modify values below or override
them at runtime via CLI flags / environment variables.

Design Rationale
----------------
Using a frozen dataclass gives us:
  • immutability after construction (catches accidental mutations)
  • type hints for IDE auto-complete
  • easy serialisation to dict / JSON for logging
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

# torch is optional at import time so that `--help` works before
# pip install.  We try to import it and fall back gracefully.
try:
    # pyrefly: ignore [missing-import]
    import torch as _torch
    _TORCH_AVAILABLE = True
except ImportError:
    _TORCH_AVAILABLE = False


# ---------------------------------------------------------------------------
#  Auto-detect compute device
# ---------------------------------------------------------------------------

def _detect_device() -> str:
    """Return 'cuda' if a CUDA-capable GPU is available, else 'cpu'."""
    if _TORCH_AVAILABLE and _torch.cuda.is_available():
        return "cuda"
    return "cpu"


# ---------------------------------------------------------------------------
#  Project root — resolved relative to THIS file so it works from any CWD
# ---------------------------------------------------------------------------

# This points to  face_blur_project/
PROJECT_ROOT = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
#  Main configuration dataclass
# ---------------------------------------------------------------------------

@dataclass
class Config:
    """Central configuration container for the face blur pipeline."""

    # ── Blur settings ─────────────────────────────────────────────────────
    # "gaussian" applies a dynamically-sized Gaussian kernel.
    # "pixelate" down-scales the face region then up-scales it back.
    blur_mode: Literal["gaussian", "pixelate"] = "gaussian"

    # Base kernel size for Gaussian blur (actual size is scaled by face dim).
    gaussian_kernel_base: int = 51

    # Block size for pixelation (smaller = heavier pixelation).
    pixelate_block_size: int = 10

    # ── Detection confidence thresholds ───────────────────────────────────
    # Confidence above this → definitely blur the face.
    confidence_high: float = 0.8

    # Confidence between medium and high → rely on tracker / history.
    confidence_medium: float = 0.4

    # Below confidence_medium → ignore unless the face was tracked before.

    # ── Bounding-box padding ──────────────────────────────────────────────
    # Fractional padding added around each detected face box.
    # 0.15 means 15 % of the box width/height is added on each side.
    bbox_padding: float = 0.15

    # ── Temporal smoothing ────────────────────────────────────────────────
    # After a tracked face disappears, keep blurring for this many frames
    # to avoid revealing faces during brief detection gaps.
    temporal_smoothing_frames: int = 5

    # ── Tracker (ByteTrack via supervision) ───────────────────────────────
    # Minimum detection score for ByteTrack to consider activating a track.
    tracker_activation_threshold: float = 0.25

    # Frames a lost track is kept alive before being dropped.
    tracker_lost_buffer: int = 30

    # Minimum consecutive detections before a track is confirmed.
    tracker_min_consecutive: int = 2

    # ── Enhancement toggles ───────────────────────────────────────────────
    enhance_denoise: bool = True
    enhance_clahe: bool = True
    enhance_gamma: bool = True
    enhance_sharpen: bool = False          # off by default; enable for blurry footage

    # CLAHE clip-limit and tile grid size
    clahe_clip_limit: float = 2.0
    clahe_tile_grid: tuple = (8, 8)

    # Gamma correction target mean luminance (below this → brighten)
    gamma_low_light_threshold: float = 80.0

    # ── Device ────────────────────────────────────────────────────────────
    device: str = field(default_factory=_detect_device)

    # ── Debug ─────────────────────────────────────────────────────────────
    debug: bool = False

    # ── Paths ─────────────────────────────────────────────────────────────
    project_root: Path = PROJECT_ROOT

    @property
    def datasets_dir(self) -> Path:
        return self.project_root / "datasets"

    @property
    def datasets_videos_dir(self) -> Path:
        return self.project_root / "datasets" / "videos"

    @property
    def datasets_images_dir(self) -> Path:
        return self.project_root / "datasets" / "images"

    @property
    def datasets_downloaded_dir(self) -> Path:
        return self.project_root / "datasets" / "downloaded"

    @property
    def outputs_dir(self) -> Path:
        return self.project_root / "outputs"

    @property
    def blurred_videos_dir(self) -> Path:
        return self.project_root / "outputs" / "blurred_videos"

    @property
    def blurred_images_dir(self) -> Path:
        return self.project_root / "outputs" / "blurred_images"

    @property
    def debug_dir(self) -> Path:
        return self.project_root / "outputs" / "debug"

    @property
    def sample_inputs_dir(self) -> Path:
        return self.project_root / "sample_inputs"


# ---------------------------------------------------------------------------
#  Singleton-style default config (importable as `from app.config import cfg`)
# ---------------------------------------------------------------------------

cfg = Config()


# ======================================================================
# --- FILE: app/utils.py ---
# ======================================================================

"""
utils.py — Shared Utility Functions
====================================

Helper functions used across multiple modules:
  • logging setup
  • directory creation
  • bounding-box manipulation (pad, clamp)
  • debug frame annotation
  • device detection
"""

import logging
import sys
from pathlib import Path
from typing import List, Optional, Tuple

# pyrefly: ignore [missing-import]
import cv2
# pyrefly: ignore [missing-import]
import numpy as np



# ---------------------------------------------------------------------------
#  Logging
# ---------------------------------------------------------------------------

def setup_logging(level: int = logging.INFO) -> logging.Logger:
    """
    Configure and return the root project logger.

    Logs go to both stdout and a file (outputs/debug/pipeline.log).

    Parameters
    ----------
    level : int
        Logging level (default: INFO).

    Returns
    -------
    logging.Logger
        Configured logger instance.
    """
    logger = logging.getLogger("face_blur")
    logger.setLevel(level)

    # Avoid duplicate handlers if called multiple times
    if logger.handlers:
        return logger

    formatter = logging.Formatter(
        "[%(asctime)s] %(levelname)-8s %(name)s — %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    # Fix for Windows console UnicodeEncodeError with emojis (✓, →, etc)
    if sys.stdout.encoding.lower() != 'utf-8':
        try:
            sys.stdout.reconfigure(encoding='utf-8')
        except AttributeError:
            pass

    # Console handler
    console = logging.StreamHandler(sys.stdout)
    console.setLevel(level)
    console.setFormatter(formatter)
    logger.addHandler(console)

    # File handler (inside debug output directory)
    log_dir = cfg.debug_dir
    log_dir.mkdir(parents=True, exist_ok=True)
    file_handler = logging.FileHandler(log_dir / "pipeline.log", encoding="utf-8")
    file_handler.setLevel(level)
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

    return logger


# ---------------------------------------------------------------------------
#  Directory helpers
# ---------------------------------------------------------------------------

def ensure_dirs() -> None:
    """Create all required output / dataset directories if they don't exist."""
    dirs = [
        cfg.datasets_videos_dir,
        cfg.datasets_images_dir,
        cfg.datasets_downloaded_dir,
        cfg.blurred_videos_dir,
        cfg.blurred_images_dir,
        cfg.debug_dir,
        cfg.sample_inputs_dir,
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
#  Bounding-box utilities
# ---------------------------------------------------------------------------

def clamp_bbox(
    bbox: Tuple[int, int, int, int],
    frame_shape: Tuple[int, int],
) -> Tuple[int, int, int, int]:
    """
    Clamp a bounding box (x1, y1, x2, y2) so it stays within frame bounds.

    Parameters
    ----------
    bbox : tuple of int
        (x1, y1, x2, y2) pixel coordinates.
    frame_shape : tuple of int
        (height, width) of the frame.

    Returns
    -------
    tuple of int
        Clamped (x1, y1, x2, y2).
    """
    h, w = frame_shape[:2]
    x1, y1, x2, y2 = bbox
    x1 = max(0, int(x1))
    y1 = max(0, int(y1))
    x2 = min(w, int(x2))
    y2 = min(h, int(y2))
    return (x1, y1, x2, y2)


def pad_bbox(
    bbox: Tuple[int, int, int, int],
    padding: float,
    frame_shape: Tuple[int, int],
) -> Tuple[int, int, int, int]:
    """
    Expand a bounding box by a fractional *padding* on each side,
    then clamp to frame bounds.

    Parameters
    ----------
    bbox : tuple of int
        (x1, y1, x2, y2).
    padding : float
        Fraction of box width/height to add (e.g. 0.15 → 15 %).
    frame_shape : tuple of int
        (height, width).

    Returns
    -------
    tuple of int
        Padded and clamped (x1, y1, x2, y2).
    """
    x1, y1, x2, y2 = bbox
    bw = x2 - x1
    bh = y2 - y1
    pad_x = int(bw * padding)
    pad_y = int(bh * padding)
    return clamp_bbox((x1 - pad_x, y1 - pad_y, x2 + pad_x, y2 + pad_y), frame_shape)


# ---------------------------------------------------------------------------
#  Debug annotation
# ---------------------------------------------------------------------------

def draw_debug_frame(
    frame: np.ndarray,
    bboxes: List[Tuple[int, int, int, int]],
    confidences: Optional[List[float]] = None,
    tracker_ids: Optional[List[int]] = None,
) -> np.ndarray:
    """
    Draw detection boxes, confidence scores, and tracker IDs on a frame copy.

    This is used to generate the debug visualisation saved to outputs/debug/.

    Parameters
    ----------
    frame : np.ndarray
        BGR frame.
    bboxes : list of (x1, y1, x2, y2)
        Face bounding boxes.
    confidences : list of float, optional
        Per-box detection confidence.
    tracker_ids : list of int, optional
        Per-box tracker ID.

    Returns
    -------
    np.ndarray
        Annotated copy of the frame (original is not modified).
    """
    debug = frame.copy()
    for i, (x1, y1, x2, y2) in enumerate(bboxes):
        # Choose colour: green for high-confidence, yellow for medium, red for low
        conf = confidences[i] if confidences else 1.0
        if conf >= cfg.confidence_high:
            colour = (0, 255, 0)       # green
        elif conf >= cfg.confidence_medium:
            colour = (0, 255, 255)     # yellow
        else:
            colour = (0, 0, 255)       # red

        # Draw rectangle
        cv2.rectangle(debug, (int(x1), int(y1)), (int(x2), int(y2)), colour, 2)

        # Build label string
        parts: List[str] = []
        if tracker_ids and i < len(tracker_ids):
            parts.append(f"ID:{tracker_ids[i]}")
        if confidences and i < len(confidences):
            parts.append(f"{confidences[i]:.2f}")
        label = " | ".join(parts)

        if label:
            # Background for text
            (tw, th), _ = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX, 0.5, 1)
            cv2.rectangle(
                debug,
                (int(x1), int(y1) - th - 8),
                (int(x1) + tw + 4, int(y1)),
                colour,
                -1,
            )
            cv2.putText(
                debug, label,
                (int(x1) + 2, int(y1) - 4),
                cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA,
            )

    return debug


# ---------------------------------------------------------------------------
#  Device helper
# ---------------------------------------------------------------------------

def get_device() -> str:
    """Return the compute device string ('cuda' or 'cpu')."""
    return cfg.device


# ======================================================================
# --- FILE: app/enhance.py ---
# ======================================================================

"""
enhance.py — Frame Enhancement / Preprocessing Pipeline
========================================================

Before feeding frames to the face detector, we apply a series of
image-enhancement steps that improve detection accuracy on challenging
surveillance footage:

    1. **Denoise** — reduce sensor / compression noise with
       ``cv2.fastNlMeansDenoisingColored``.
    2. **CLAHE** — Contrast-Limited Adaptive Histogram Equalisation on
       the L channel (LAB colour space) to boost local contrast.
    3. **Gamma correction** — brighten under-exposed (low-light) frames
       by estimating mean luminance and adjusting gamma.
    4. **Sharpen** (optional) — unsharp-mask to recover detail from
       motion-blurred or out-of-focus frames.

Each step can be toggled independently via ``config.py``.

Why these steps matter
----------------------
Surveillance cameras often produce images with:
  • poor lighting (IR or dim corridors)
  • heavy JPEG/H.264 compression artefacts
  • motion blur from low shutter speeds

Deep-learning detectors like RetinaFace are *much* more robust than
classical Haar cascades, but they still benefit from clean input.
These lightweight OpenCV operations add <2 ms per frame on CPU.
"""

# pyrefly: ignore [missing-import]
import cv2
# pyrefly: ignore [missing-import]
import numpy as np
import logging


logger = logging.getLogger("face_blur.enhance")


class FrameEnhancer:
    """
    Stateless image-enhancement pipeline.

    Usage
    -----
    >>> enhancer = FrameEnhancer()
    >>> clean_frame = enhancer.enhance(raw_frame)
    """

    def __init__(self, config=None):
        """
        Parameters
        ----------
        config : Config, optional
            Override the global config (useful for testing).
        """
        self.cfg = config or cfg

        # Pre-create the CLAHE object (reusable across frames)
        if self.cfg.enhance_clahe:
            self._clahe = cv2.createCLAHE(
                clipLimit=self.cfg.clahe_clip_limit,
                tileGridSize=self.cfg.clahe_tile_grid,
            )
        else:
            self._clahe = None

    # ------------------------------------------------------------------
    #  Public API
    # ------------------------------------------------------------------

    def enhance(self, frame: np.ndarray) -> np.ndarray:
        """
        Run the full enhancement pipeline on a single BGR frame.

        Parameters
        ----------
        frame : np.ndarray
            Input BGR image (H×W×3, uint8).

        Returns
        -------
        np.ndarray
            Enhanced BGR image, same shape.
        """
        result = frame.copy()

        # Step 1 — Denoise
        if self.cfg.enhance_denoise:
            result = self._denoise(result)

        # Step 2 — CLAHE contrast enhancement
        if self.cfg.enhance_clahe and self._clahe is not None:
            result = self._apply_clahe(result)

        # Step 3 — Gamma correction for low-light frames
        if self.cfg.enhance_gamma:
            result = self._gamma_correct(result)

        # Step 4 — Optional sharpening
        if self.cfg.enhance_sharpen:
            result = self._sharpen(result)

        return result

    # ------------------------------------------------------------------
    #  Private helpers
    # ------------------------------------------------------------------

    def _denoise(self, frame: np.ndarray) -> np.ndarray:
        """
        Apply fast non-local-means denoising (colour variant).

        Parameters are tuned for surveillance-grade noise levels:
          h=6  → filter strength for luminance
          hForColorComponents=6  → filter strength for chrominance
          templateWindowSize=7   → patch size
          searchWindowSize=21    → search area
        """
        return cv2.fastNlMeansDenoisingColored(
            frame,
            None,
            h=6,
            hColor=6,
            templateWindowSize=7,
            searchWindowSize=21,
        )

    def _apply_clahe(self, frame: np.ndarray) -> np.ndarray:
        """
        Apply CLAHE on the L channel of the LAB colour space.

        This boosts local contrast without over-saturating colours,
        which is critical for CCTV footage with uneven lighting.
        """
        lab = cv2.cvtColor(frame, cv2.COLOR_BGR2LAB)
        l_channel, a_channel, b_channel = cv2.split(lab)

        # Apply CLAHE only to the luminance channel
        l_enhanced = self._clahe.apply(l_channel)

        lab_enhanced = cv2.merge([l_enhanced, a_channel, b_channel])
        return cv2.cvtColor(lab_enhanced, cv2.COLOR_LAB2BGR)

    def _gamma_correct(self, frame: np.ndarray) -> np.ndarray:
        """
        Automatically brighten dark frames using gamma correction.

        Algorithm:
          1. Convert to grayscale and compute mean luminance.
          2. If mean < threshold (low light), compute a gamma < 1.0
             to brighten the image.
          3. Apply a look-up table for O(1) per-pixel transform.
        """
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        mean_luminance = np.mean(gray)

        if mean_luminance >= self.cfg.gamma_low_light_threshold:
            # Frame is bright enough — skip correction
            return frame

        # Compute gamma: lower mean → lower gamma → more brightening
        # Clamp gamma to [0.3, 1.0] to avoid extreme brightening
        gamma = max(0.3, mean_luminance / self.cfg.gamma_low_light_threshold)

        logger.debug(
            "Low-light frame detected (mean=%.1f). Applying gamma=%.2f",
            mean_luminance, gamma,
        )

        # Build look-up table
        inv_gamma = 1.0 / gamma
        table = np.array(
            [((i / 255.0) ** inv_gamma) * 255 for i in range(256)],
            dtype=np.uint8,
        )
        return cv2.LUT(frame, table)

    def _sharpen(self, frame: np.ndarray) -> np.ndarray:
        """
        Apply unsharp masking to recover detail from blurry frames.

        Unsharp mask = original + alpha * (original − blurred)
        """
        blurred = cv2.GaussianBlur(frame, (0, 0), sigmaX=3)
        # alpha=1.5 gives moderate sharpening; beta=-0.5 subtracts the blur
        sharpened = cv2.addWeighted(frame, 1.5, blurred, -0.5, 0)
        return sharpened


# ======================================================================
# --- FILE: app/detector.py ---
# ======================================================================

"""
detector.py — Deep-Learning Face Detection
============================================

Uses **InsightFace** with the ``buffalo_l`` model bundle (which includes
a RetinaFace-based detector) to locate every visible human face in a
frame.

Why InsightFace / RetinaFace instead of Haar Cascades?
------------------------------------------------------
• **Haar cascades** are classical ML (Viola-Jones).  They are fast but
  have *very* high false-negative rates on:
    – side-profile faces  (cascade is frontal-only)
    – partially occluded faces
    – small / distant faces
    – low-light / noisy images
  They also produce many false positives on texture-rich backgrounds.

• **RetinaFace** (deep learning, anchor-based dense regression) was
  specifically designed for "in-the-wild" face detection.  Advantages:
    – State-of-the-art accuracy on WIDER FACE benchmark
    – Handles extreme poses (profile, up/down)
    – Detects very small faces (down to ~10 px)
    – Provides 5-point facial landmarks (useful for alignment)
    – Single forward pass — GPU-accelerated

• **InsightFace ``buffalo_l``** bundles RetinaFace detection + ArcFace
  recognition in one download.  We only use the *detection* part.

Confidence-based filtering
--------------------------
The detector returns every face with its confidence score.  We classify
detections into three tiers (thresholds in ``config.py``):

    HIGH  (> 0.8)   → definitely blur
    MEDIUM (0.4–0.8) → soft detection, needs tracker confirmation
    LOW   (< 0.4)   → ignored unless previously tracked

This prevents both missed faces and over-aggressive false positives.
"""

import logging
from dataclasses import dataclass
from typing import List, Optional, Tuple

# pyrefly: ignore [missing-import]
import numpy as np


logger = logging.getLogger("face_blur.detector")


# ---------------------------------------------------------------------------
#  Data container for a single detection
# ---------------------------------------------------------------------------

@dataclass
class Detection:
    """
    One detected face.

    Attributes
    ----------
    bbox : tuple of int
        (x1, y1, x2, y2) bounding box in pixel coordinates.
    confidence : float
        Detection confidence in [0, 1].
    landmarks : np.ndarray or None
        5-point facial landmarks (eyes, nose, mouth corners).
    tier : str
        Classification: 'high', 'medium', or 'low'.
    """
    bbox: Tuple[int, int, int, int]
    confidence: float
    landmarks: Optional[np.ndarray] = None
    tier: str = "high"


# ---------------------------------------------------------------------------
#  Face Detector
# ---------------------------------------------------------------------------

class FaceDetector:
    """
    Wrapper around InsightFace's FaceAnalysis for face detection.

    Usage
    -----
    >>> detector = FaceDetector()
    >>> detections = detector.detect(bgr_frame)
    """

    def __init__(self, config=None):
        """
        Initialise the InsightFace model.

        Parameters
        ----------
        config : Config, optional
            Override the global config.
        """
        self.cfg = config or cfg

        # Lazy-import insightface so we get a clear error if not installed
        try:
            # pyrefly: ignore [missing-import]
            from insightface.app import FaceAnalysis
        except ImportError as exc:
            raise ImportError(
                "InsightFace is required.  Install it with:\n"
                "    pip install insightface onnxruntime-gpu\n"
                "or  pip install insightface onnxruntime  (CPU-only)"
            ) from exc

        logger.info("Initialising InsightFace detector (model=buffalo_l) …")

        # Create the FaceAnalysis app
        # 'buffalo_l' = large model bundle with RetinaFace + ArcFace
        # We only need the detection part (det_size controls input resolution)
        self._app = FaceAnalysis(
            name="buffalo_l",
            providers=self._get_providers(),
        )

        # Prepare with detection size — larger = more accurate but slower
        # 640×640 is the standard; works well for surveillance
        self._app.prepare(ctx_id=0 if self.cfg.device == "cuda" else -1,
                          det_size=(640, 640))

        logger.info("InsightFace detector ready (device=%s)", self.cfg.device)

    # ------------------------------------------------------------------
    #  Public API
    # ------------------------------------------------------------------

    def detect(self, frame: np.ndarray) -> List[Detection]:
        """
        Detect all faces in a BGR frame.

        Parameters
        ----------
        frame : np.ndarray
            Input BGR image (H×W×3, uint8).

        Returns
        -------
        list of Detection
            Detected faces with bounding boxes, confidences, and landmarks.
        """
        # InsightFace expects BGR (which OpenCV already provides)
        faces = self._app.get(frame)

        detections: List[Detection] = []
        for face in faces:
            # face.bbox is a numpy array [x1, y1, x2, y2]
            raw_bbox = face.bbox.astype(int)
            conf = float(face.det_score)

            # Classify confidence tier
            tier = self._classify_confidence(conf)

            # Apply safety padding and clamp to frame bounds
            padded = pad_bbox(
                tuple(raw_bbox),
                self.cfg.bbox_padding,
                frame.shape[:2],
            )

            detections.append(Detection(
                bbox=padded,
                confidence=conf,
                landmarks=face.kps if hasattr(face, "kps") else None,
                tier=tier,
            ))

        logger.debug("Detected %d faces (frame shape=%s)", len(detections), frame.shape[:2])
        return detections

    # ------------------------------------------------------------------
    #  Private helpers
    # ------------------------------------------------------------------

    def _classify_confidence(self, conf: float) -> str:
        """Map a confidence score to a tier string."""
        if conf >= self.cfg.confidence_high:
            return "high"
        elif conf >= self.cfg.confidence_medium:
            return "medium"
        else:
            return "low"

    def _get_providers(self) -> list:
        """
        Return the ONNX Runtime execution providers in priority order.

        If CUDA is available we prefer CUDAExecutionProvider, otherwise
        fall back to CPU.
        """
        if self.cfg.device == "cuda":
            return ["CUDAExecutionProvider", "CPUExecutionProvider"]
        return ["CPUExecutionProvider"]


# ======================================================================
# --- FILE: app/tracker.py ---
# ======================================================================

"""
tracker.py — Multi-Object Face Tracking with ByteTrack
=======================================================

Wraps the **ByteTrack** implementation from the ``supervision`` library
to maintain persistent face identities across video frames.

Why tracking matters for face blurring
--------------------------------------
Without tracking, the detector runs independently on each frame.  This
causes two problems:

1. **Flickering** — a face that's detected on frame N, missed on frame
   N+1, and detected again on frame N+2 will flicker between blurred
   and un-blurred.  This can reveal a person's identity in a single
   un-blurred frame.

2. **Uncertain detections** — a medium-confidence detection (0.4–0.8)
   on its own is risky to blur (could be a false positive).  But if the
   tracker shows that box has been consistently detected for 10 frames,
   we can blur it with high confidence.

ByteTrack key ideas
-------------------
ByteTrack uses a two-stage association strategy:
  • First match *high*-confidence detections to existing tracks.
  • Then match *low*-confidence detections to remaining unmatched tracks.
This recovers partially occluded or blurry faces that other trackers
would drop.  Perfect for surveillance footage.

Temporal smoothing
------------------
After a tracked face disappears, we keep its last known bounding box
and continue blurring for ``temporal_smoothing_frames`` additional
frames.  This prevents brief "flash" reveals.
"""

import logging
import warnings
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

# pyrefly: ignore [missing-import]
import numpy as np


logger = logging.getLogger("face_blur.tracker")


# ---------------------------------------------------------------------------
#  Data container for a tracked face
# ---------------------------------------------------------------------------

@dataclass
class TrackedFace:
    """
    A face detection augmented with a persistent tracker ID and
    temporal-smoothing metadata.
    """
    bbox: Tuple[int, int, int, int]
    confidence: float
    tracker_id: int
    tier: str = "high"
    landmarks: Optional[np.ndarray] = None
    frames_since_seen: int = 0          # 0 = just detected this frame


# ---------------------------------------------------------------------------
#  Face Tracker
# ---------------------------------------------------------------------------

class FaceTracker:
    """
    Wraps ``supervision.ByteTrack`` and adds temporal smoothing.

    Usage
    -----
    >>> tracker = FaceTracker()
    >>> for frame in video:
    ...     detections = detector.detect(frame)
    ...     tracked = tracker.update(detections, frame.shape[:2])
    ...     blurred = blurrer.blur_faces(frame, tracked)
    """

    def __init__(self, config=None):
        """
        Parameters
        ----------
        config : Config, optional
            Override the global config.
        """
        self.cfg = config or cfg

        # Lazy-import supervision
        try:
            # pyrefly: ignore [missing-import]
            import supervision as sv
        except ImportError as exc:
            raise ImportError(
                "The 'supervision' library is required for tracking.\n"
                "    pip install supervision"
            ) from exc

        # Initialise ByteTrack from the supervision library
        # NOTE: ByteTrack is deprecated in supervision>=0.28 in favour of
        # the standalone 'trackers' package.  We suppress the warning here;
        # migrate to `from trackers import ByteTrackTracker` when upgrading.
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", FutureWarning)
            self._tracker = sv.ByteTrack(
                track_activation_threshold=self.cfg.tracker_activation_threshold,
                lost_track_buffer=self.cfg.tracker_lost_buffer,
                minimum_matching_threshold=0.8,
                frame_rate=30,
                minimum_consecutive_frames=self.cfg.tracker_min_consecutive,
            )

        # ── Temporal smoothing state ──────────────────────────────────
        # Maps tracker_id → TrackedFace from the most recent detection.
        # When a track disappears, we keep it here and increment
        # frames_since_seen each frame until it exceeds the threshold.
        self._last_seen: Dict[int, TrackedFace] = {}

        logger.info(
            "ByteTrack tracker initialised (activation=%.2f, buffer=%d, "
            "min_consecutive=%d, temporal_smooth=%d frames)",
            self.cfg.tracker_activation_threshold,
            self.cfg.tracker_lost_buffer,
            self.cfg.tracker_min_consecutive,
            self.cfg.temporal_smoothing_frames,
        )

    # ------------------------------------------------------------------
    #  Public API
    # ------------------------------------------------------------------

    def update(
        self,
        detections: List[Detection],
        frame_shape: Tuple[int, int],
    ) -> List[TrackedFace]:
        """
        Feed new detections into the tracker and return tracked faces.

        Confidence-based logic
        ----------------------
        • HIGH-tier detections are always passed to the tracker.
        • MEDIUM-tier detections are passed to the tracker (ByteTrack's
          two-stage matching will confirm or reject them).
        • LOW-tier detections are only included if they match an
          *existing* track (checked after the tracker runs).

        After the tracker runs, we apply temporal smoothing to continue
        blurring recently lost tracks.

        Parameters
        ----------
        detections : list of Detection
            Raw detections from the detector.
        frame_shape : tuple of int
            (height, width) of the current frame.

        Returns
        -------
        list of TrackedFace
            Faces to blur this frame, with persistent tracker IDs.
        """
        # pyrefly: ignore [missing-import]
        import supervision as sv

        # ── Separate detections by tier ──────────────────────────────
        high_medium = [d for d in detections if d.tier in ("high", "medium")]
        low = [d for d in detections if d.tier == "low"]

        # ── Build a supervision Detections object ────────────────────
        if high_medium:
            xyxy = np.array([d.bbox for d in high_medium], dtype=np.float32)
            confs = np.array([d.confidence for d in high_medium], dtype=np.float32)
            sv_dets = sv.Detections(
                xyxy=xyxy,
                confidence=confs,
            )
        else:
            sv_dets = sv.Detections.empty()

        # ── Run ByteTrack ────────────────────────────────────────────
        tracked_sv = self._tracker.update_with_detections(sv_dets)

        # ── Build result list ────────────────────────────────────────
        active_ids = set()
        results: List[TrackedFace] = []

        if tracked_sv.tracker_id is not None:
            for i in range(len(tracked_sv)):
                tid = int(tracked_sv.tracker_id[i])
                bbox = tuple(tracked_sv.xyxy[i].astype(int))
                conf = float(tracked_sv.confidence[i]) if tracked_sv.confidence is not None else 1.0

                tf = TrackedFace(
                    bbox=bbox,
                    confidence=conf,
                    tracker_id=tid,
                    tier="high" if conf >= self.cfg.confidence_high else "medium",
                    frames_since_seen=0,
                )
                results.append(tf)
                active_ids.add(tid)

                # Update last-seen map
                self._last_seen[tid] = tf

        # ── Handle LOW-tier detections that match existing tracks ────
        # If a low-confidence detection overlaps significantly with a
        # known track, we include it (the tracker already handles most
        # of this, but this is a safety net).
        for d in low:
            for tid, prev in self._last_seen.items():
                if tid in active_ids:
                    continue
                if self._iou(d.bbox, prev.bbox) > 0.3:
                    # Reuse the tracked ID
                    tf = TrackedFace(
                        bbox=d.bbox,
                        confidence=d.confidence,
                        tracker_id=tid,
                        tier="low",
                        frames_since_seen=0,
                    )
                    results.append(tf)
                    active_ids.add(tid)
                    self._last_seen[tid] = tf
                    break

        # ── Temporal smoothing: keep recently lost tracks ────────────
        for tid, prev in list(self._last_seen.items()):
            if tid in active_ids:
                continue  # still active, skip

            prev.frames_since_seen += 1
            if prev.frames_since_seen <= self.cfg.temporal_smoothing_frames:
                # Continue blurring at the last known position
                results.append(prev)
                active_ids.add(tid)
                logger.debug(
                    "Temporal smooth: track %d frame %d/%d",
                    tid, prev.frames_since_seen,
                    self.cfg.temporal_smoothing_frames,
                )
            else:
                # Track has been gone too long — remove
                del self._last_seen[tid]

        logger.debug(
            "Tracker update: %d active tracks, %d smoothed",
            len([r for r in results if r.frames_since_seen == 0]),
            len([r for r in results if r.frames_since_seen > 0]),
        )
        return results

    def reset(self) -> None:
        """Reset the tracker state (e.g. when switching to a new video)."""
        self._last_seen.clear()
        # Re-create the ByteTrack instance
        # pyrefly: ignore [missing-import]
        import supervision as sv
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", FutureWarning)
            self._tracker = sv.ByteTrack(
                track_activation_threshold=self.cfg.tracker_activation_threshold,
                lost_track_buffer=self.cfg.tracker_lost_buffer,
                minimum_matching_threshold=0.8,
                frame_rate=30,
                minimum_consecutive_frames=self.cfg.tracker_min_consecutive,
            )
        logger.info("Tracker state reset.")

    # ------------------------------------------------------------------
    #  Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _iou(
        box_a: Tuple[int, int, int, int],
        box_b: Tuple[int, int, int, int],
    ) -> float:
        """
        Compute Intersection-over-Union between two boxes (x1, y1, x2, y2).
        """
        x1 = max(box_a[0], box_b[0])
        y1 = max(box_a[1], box_b[1])
        x2 = min(box_a[2], box_b[2])
        y2 = min(box_a[3], box_b[3])

        inter = max(0, x2 - x1) * max(0, y2 - y1)
        area_a = (box_a[2] - box_a[0]) * (box_a[3] - box_a[1])
        area_b = (box_b[2] - box_b[0]) * (box_b[3] - box_b[1])
        union = area_a + area_b - inter

        return inter / union if union > 0 else 0.0


# ======================================================================
# --- FILE: app/blur.py ---
# ======================================================================

"""
blur.py — Face Blurring / Anonymisation
========================================

Applies blur to detected face regions.  Two modes are supported:

1. **Gaussian blur** — classic privacy technique.  The kernel size is
   scaled dynamically based on the face bounding-box dimensions so that
   large faces get heavier blur and small faces still look anonymised.

2. **Pixelation** — down-scales the face region to a tiny resolution
   and then up-scales it back, creating a mosaic / pixel-art effect.

The mode is controlled via ``config.blur_mode`` (``"gaussian"`` or
``"pixelate"``).

Both modes operate in-place on the frame for performance, but the
public API returns the modified frame for chaining.
"""

import logging
from typing import List, Union

# pyrefly: ignore [missing-import]
import cv2
# pyrefly: ignore [missing-import]
import numpy as np


logger = logging.getLogger("face_blur.blur")


class FaceBlurrer:
    """
    Apply Gaussian or pixelation blur to face bounding boxes.

    Usage
    -----
    >>> blurrer = FaceBlurrer()
    >>> blurred_frame = blurrer.blur_faces(frame, tracked_faces)
    """

    def __init__(self, config=None):
        """
        Parameters
        ----------
        config : Config, optional
            Override the global config.
        """
        self.cfg = config or cfg

    # ------------------------------------------------------------------
    #  Public API
    # ------------------------------------------------------------------

    def blur_faces(
        self,
        frame: np.ndarray,
        faces: List[Union[Detection, TrackedFace]],
    ) -> np.ndarray:
        """
        Blur every face in *faces* on the given frame.

        Parameters
        ----------
        frame : np.ndarray
            BGR frame (modified in-place AND returned).
        faces : list
            Detection or TrackedFace objects with ``.bbox`` attribute.

        Returns
        -------
        np.ndarray
            The frame with faces blurred.
        """
        for face in faces:
            x1, y1, x2, y2 = clamp_bbox(face.bbox, frame.shape[:2])

            # Skip degenerate boxes
            if x2 <= x1 or y2 <= y1:
                continue

            # Extract face region-of-interest
            roi = frame[y1:y2, x1:x2]

            if self.cfg.blur_mode == "pixelate":
                blurred_roi = self._pixelate(roi)
            else:
                blurred_roi = self._gaussian_blur(roi)

            # Write back
            frame[y1:y2, x1:x2] = blurred_roi

        return frame

    # ------------------------------------------------------------------
    #  Blur implementations
    # ------------------------------------------------------------------

    def _gaussian_blur(self, roi: np.ndarray) -> np.ndarray:
        """
        Apply Gaussian blur with a kernel size scaled to the face size.

        The kernel size is derived from the largest dimension of the ROI:
            k = max(w, h) // 2 * 2 + 1   (ensures odd number)
        Minimum kernel is 15 to guarantee visible anonymisation.

        A larger face → larger kernel → heavier blur, so the face
        remains unrecognisable regardless of its apparent size.
        """
        h, w = roi.shape[:2]

        # Dynamic kernel size based on face dimensions
        k = max(w, h) // 2
        k = max(k, 15)                   # minimum kernel size
        k = k if k % 2 == 1 else k + 1   # must be odd

        # Sigma=0 → OpenCV auto-computes sigma from kernel size
        return cv2.GaussianBlur(roi, (k, k), 0)

    def _pixelate(self, roi: np.ndarray) -> np.ndarray:
        """
        Pixelate by down-scaling then up-scaling the face region.

        The block size controls how many pixels each "super-pixel"
        covers.  Smaller block_size → heavier pixelation.

        Steps:
            1. Shrink the ROI to (w/block, h/block) using INTER_LINEAR
            2. Scale it back to original size using INTER_NEAREST
               (nearest-neighbour preserves the blocky look)
        """
        h, w = roi.shape[:2]
        block = self.cfg.pixelate_block_size

        # Down-scale
        small_w = max(1, w // block)
        small_h = max(1, h // block)
        small = cv2.resize(roi, (small_w, small_h), interpolation=cv2.INTER_LINEAR)

        # Up-scale back to original size with nearest-neighbour
        return cv2.resize(small, (w, h), interpolation=cv2.INTER_NEAREST)


# ======================================================================
# --- FILE: app/image_processor.py ---
# ======================================================================

"""
image_processor.py — Single-Image & Batch Image Processing
============================================================

Orchestrates the full pipeline for still images:
    enhance → detect → blur → save

Supports:
  • processing a single image file
  • batch-processing every image in a directory
  • saving debug visualisations alongside the blurred output
"""

import logging
from pathlib import Path
from typing import List, Optional

# pyrefly: ignore [missing-import]
import cv2


logger = logging.getLogger("face_blur.image_processor")

# Supported image extensions (case-insensitive)
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif", ".webp"}


class ImageProcessor:
    """
    End-to-end image face-blurring processor.

    Usage
    -----
    >>> proc = ImageProcessor()
    >>> proc.process_image("sample_inputs/sample_image.jpg")
    >>> proc.process_directory("datasets/images/")
    """

    def __init__(self, config=None):
        """
        Initialise the pipeline components.

        Parameters
        ----------
        config : Config, optional
            Override the global config.
        """
        self.cfg = config or cfg

        # Create pipeline components
        self.enhancer = FrameEnhancer(self.cfg)
        self.detector = FaceDetector(self.cfg)
        self.blurrer = FaceBlurrer(self.cfg)

        ensure_dirs()
        logger.info("ImageProcessor initialised (blur_mode=%s)", self.cfg.blur_mode)

    # ------------------------------------------------------------------
    #  Public API
    # ------------------------------------------------------------------

    def process_image(
        self,
        image_path: str,
        output_dir: Optional[str] = None,
    ) -> Optional[str]:
        """
        Process a single image: enhance, detect faces, blur, save.

        Parameters
        ----------
        image_path : str
            Path to the input image.
        output_dir : str, optional
            Custom output directory.  Defaults to ``outputs/blurred_images/``.

        Returns
        -------
        str or None
            Path to the saved blurred image, or None on failure.
        """
        image_path = Path(image_path)
        if not image_path.exists():
            logger.error("Image not found: %s", image_path)
            return None

        out_dir = Path(output_dir) if output_dir else self.cfg.blurred_images_dir
        out_dir.mkdir(parents=True, exist_ok=True)

        logger.info("Processing image: %s", image_path.name)

        # ── Load image ────────────────────────────────────────────────
        frame = cv2.imread(str(image_path))
        if frame is None:
            logger.error("Failed to read image: %s", image_path)
            return None

        # ── Enhance ───────────────────────────────────────────────────
        enhanced = self.enhancer.enhance(frame)

        # ── Detect faces ──────────────────────────────────────────────
        detections = self.detector.detect(enhanced)
        logger.info(
            "  Found %d faces (high=%d, medium=%d, low=%d)",
            len(detections),
            sum(1 for d in detections if d.tier == "high"),
            sum(1 for d in detections if d.tier == "medium"),
            sum(1 for d in detections if d.tier == "low"),
        )

        # For images, we blur HIGH and MEDIUM detections (no tracker context)
        faces_to_blur = [d for d in detections if d.tier in ("high", "medium")]

        # ── Blur faces ────────────────────────────────────────────────
        blurred = self.blurrer.blur_faces(frame.copy(), faces_to_blur)

        # ── Save output ──────────────────────────────────────────────
        output_name = f"blurred_{image_path.stem}.jpg"
        output_path = out_dir / output_name
        cv2.imwrite(str(output_path), blurred)
        logger.info("  Saved blurred image → %s", output_path)

        # ── Save debug output ────────────────────────────────────────
        if self.cfg.debug:
            self._save_debug(frame, detections, image_path.stem)

        return str(output_path)

    def process_directory(
        self,
        input_dir: str,
        output_dir: Optional[str] = None,
    ) -> List[str]:
        """
        Batch-process all images in a directory.

        Parameters
        ----------
        input_dir : str
            Directory containing images.
        output_dir : str, optional
            Custom output directory.

        Returns
        -------
        list of str
            Paths to all saved blurred images.
        """
        input_dir = Path(input_dir)
        if not input_dir.is_dir():
            logger.error("Input directory not found: %s", input_dir)
            return []

        # Gather image files
        image_files = sorted(
            f for f in input_dir.iterdir()
            if f.suffix.lower() in IMAGE_EXTENSIONS
        )

        if not image_files:
            logger.warning("No images found in %s", input_dir)
            return []

        logger.info("Batch processing %d images from %s", len(image_files), input_dir)
        results = []
        for img_path in image_files:
            result = self.process_image(str(img_path), output_dir)
            if result:
                results.append(result)

        logger.info("Batch complete: %d/%d images processed", len(results), len(image_files))
        return results

    # ------------------------------------------------------------------
    #  Private helpers
    # ------------------------------------------------------------------

    def _save_debug(self, frame, detections, stem):
        """Save a debug visualisation with detection boxes and confidence scores."""
        debug_dir = self.cfg.debug_dir
        debug_dir.mkdir(parents=True, exist_ok=True)

        bboxes = [d.bbox for d in detections]
        confs = [d.confidence for d in detections]

        debug_frame = draw_debug_frame(frame, bboxes, confs)
        debug_path = debug_dir / f"debug_{stem}.jpg"
        cv2.imwrite(str(debug_path), debug_frame)
        logger.info("  Saved debug image → %s", debug_path)


# ======================================================================
# --- FILE: app/video_processor.py ---
# ======================================================================

"""
video_processor.py — End-to-End Video Face-Blurring Pipeline
=============================================================

Orchestrates the full pipeline for video files:
    read frames → enhance → detect → track → blur → write MP4

Key features:
  • Preserves original FPS and resolution
  • Uses ByteTrack for persistent face tracking
  • Applies temporal smoothing to prevent flicker
  • Saves debug frames with detection boxes / tracker IDs
  • Muxes original audio track back into the output using ffmpeg
  • Progress bar via tqdm

Output format is always MP4 (H.264 via OpenCV or ffmpeg fallback).
"""

import logging
import shutil
import subprocess
from pathlib import Path
from typing import Optional

# pyrefly: ignore [missing-import]
import cv2
# pyrefly: ignore [missing-import]
from tqdm import tqdm


logger = logging.getLogger("face_blur.video_processor")


class VideoProcessor:
    """
    End-to-end video face-blurring processor.

    Usage
    -----
    >>> proc = VideoProcessor()
    >>> proc.process_video("sample_inputs/sample_video.mp4")
    """

    def __init__(self, config=None):
        """
        Initialise all pipeline components.

        Parameters
        ----------
        config : Config, optional
            Override the global config.
        """
        self.cfg = config or cfg

        # Pipeline components
        self.enhancer = FrameEnhancer(self.cfg)
        self.detector = FaceDetector(self.cfg)
        self.tracker = FaceTracker(self.cfg)
        self.blurrer = FaceBlurrer(self.cfg)

        ensure_dirs()
        logger.info(
            "VideoProcessor initialised (blur_mode=%s, device=%s)",
            self.cfg.blur_mode, self.cfg.device,
        )

    # ------------------------------------------------------------------
    #  Public API
    # ------------------------------------------------------------------

    def process_video(
        self,
        video_path: str,
        output_dir: Optional[str] = None,
    ) -> Optional[str]:
        """
        Process a single video file: read → enhance → detect → track →
        blur → write MP4 → mux audio.

        Parameters
        ----------
        video_path : str
            Path to the input video.
        output_dir : str, optional
            Custom output directory.  Defaults to ``outputs/blurred_videos/``.

        Returns
        -------
        str or None
            Path to the saved blurred MP4, or None on failure.
        """
        video_path = Path(video_path)
        if not video_path.exists():
            logger.error("Video not found: %s", video_path)
            return None

        out_dir = Path(output_dir) if output_dir else self.cfg.blurred_videos_dir
        out_dir.mkdir(parents=True, exist_ok=True)

        # ── Open input video ─────────────────────────────────────────
        cap = cv2.VideoCapture(str(video_path))
        if not cap.isOpened():
            logger.error("Failed to open video: %s", video_path)
            return None

        # Read video metadata
        fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

        logger.info(
            "Processing video: %s (%dx%d @ %.1f FPS, %d frames)",
            video_path.name, width, height, fps, total_frames,
        )

        # ── Prepare output video writer ──────────────────────────────
        # We write to a temp file first, then mux audio and move
        output_name = f"blurred_{video_path.stem}.mp4"
        final_output = out_dir / output_name

        # Use mp4v codec (widely supported H.264 alternative)
        # If H.264 is available via ffmpeg, we'll re-encode later
        temp_output = out_dir / f"_temp_{output_name}"

        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        writer = cv2.VideoWriter(str(temp_output), fourcc, fps, (width, height))

        if not writer.isOpened():
            logger.error("Failed to create video writer for %s", temp_output)
            cap.release()
            return None

        # ── Reset tracker for this video ─────────────────────────────
        self.tracker.reset()

        # ── Debug writer (optional) ──────────────────────────────────
        debug_writer = None
        if self.cfg.debug:
            debug_path = self.cfg.debug_dir / f"debug_{video_path.stem}.mp4"
            debug_writer = cv2.VideoWriter(
                str(debug_path), fourcc, fps, (width, height)
            )

        # ── Frame processing loop ────────────────────────────────────
        frame_idx = 0
        total_faces = 0

        pbar = tqdm(total=total_frames, desc=f"Blurring {video_path.name}", unit="frame")

        while True:
            ret, frame = cap.read()
            if not ret:
                break

            # Step 1 — Enhance
            enhanced = self.enhancer.enhance(frame)

            # Step 2 — Detect
            detections = self.detector.detect(enhanced)

            # Step 3 — Track (handles confidence tiers + temporal smoothing)
            tracked_faces = self.tracker.update(detections, frame.shape[:2])
            total_faces += len(tracked_faces)

            # Step 4 — Blur
            blurred = self.blurrer.blur_faces(frame.copy(), tracked_faces)

            # Step 5 — Write output frame
            writer.write(blurred)

            # Step 6 — Write debug frame (if enabled)
            if debug_writer is not None:
                bboxes = [tf.bbox for tf in tracked_faces]
                confs = [tf.confidence for tf in tracked_faces]
                tids = [tf.tracker_id for tf in tracked_faces]
                debug_frame = draw_debug_frame(frame, bboxes, confs, tids)
                debug_writer.write(debug_frame)

            frame_idx += 1
            pbar.update(1)

        pbar.close()

        # ── Clean up ─────────────────────────────────────────────────
        cap.release()
        writer.release()
        if debug_writer is not None:
            debug_writer.release()

        logger.info(
            "Processed %d frames, blurred %d face instances",
            frame_idx, total_faces,
        )

        # ── Mux audio from original video ────────────────────────────
        self._mux_audio(video_path, temp_output, final_output)

        # ── Clean up temp file ───────────────────────────────────────
        if temp_output.exists() and final_output.exists():
            temp_output.unlink()

        logger.info("Saved blurred video → %s", final_output)
        return str(final_output)

    def process_directory(
        self,
        input_dir: str,
        output_dir: Optional[str] = None,
    ) -> list:
        """
        Batch-process all MP4/AVI/MKV/MOV videos in a directory.

        Parameters
        ----------
        input_dir : str
            Directory containing video files.
        output_dir : str, optional
            Custom output directory.

        Returns
        -------
        list of str
            Paths to all saved blurred videos.
        """
        video_exts = {".mp4", ".avi", ".mkv", ".mov", ".webm"}
        input_dir = Path(input_dir)

        if not input_dir.is_dir():
            logger.error("Input directory not found: %s", input_dir)
            return []

        video_files = sorted(
            f for f in input_dir.iterdir()
            if f.suffix.lower() in video_exts
        )

        if not video_files:
            logger.warning("No video files found in %s", input_dir)
            return []

        logger.info("Batch processing %d videos from %s", len(video_files), input_dir)
        results = []
        for vpath in video_files:
            result = self.process_video(str(vpath), output_dir)
            if result:
                results.append(result)

        logger.info("Batch complete: %d/%d videos processed", len(results), len(video_files))
        return results

    # ------------------------------------------------------------------
    #  Private helpers
    # ------------------------------------------------------------------

    def _mux_audio(self, original: Path, video_only: Path, output: Path) -> None:
        """
        Use ffmpeg to copy the audio stream from *original* into *video_only*
        and write the result to *output*.

        If ffmpeg is not available or the original has no audio, we simply
        rename the video-only file to the output path.
        """
        ffmpeg_bin = shutil.which("ffmpeg")
        if ffmpeg_bin is None:
            logger.warning(
                "ffmpeg not found on PATH — output will have no audio. "
                "Install ffmpeg to preserve audio tracks."
            )
            # Just rename temp → final
            if output.exists():
                output.unlink()
            video_only.rename(output)
            return

        try:
            cmd = [
                ffmpeg_bin,
                "-y",                               # overwrite output
                "-i", str(video_only),               # blurred video (no audio)
                "-i", str(original),                 # original video (has audio)
                "-c:v", "copy",                      # copy video stream as-is
                "-c:a", "aac",                       # re-encode audio to AAC
                "-map", "0:v:0",                     # video from first input
                "-map", "1:a:0?",                    # audio from second input (optional)
                "-shortest",                         # match shortest stream
                str(output),
            ]
            logger.info("Muxing audio with ffmpeg …")
            result = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=300,
            )
            if result.returncode != 0:
                logger.warning(
                    "ffmpeg audio mux failed (rc=%d). Output will have no audio.\n%s",
                    result.returncode, result.stderr.decode(errors="replace")[:500],
                )
                # Fall back: just rename
                if output.exists():
                    output.unlink()
                video_only.rename(output)
        except FileNotFoundError:
            logger.warning("ffmpeg binary not found — skipping audio mux.")
            if output.exists():
                output.unlink()
            video_only.rename(output)
        except subprocess.TimeoutExpired:
            logger.warning("ffmpeg timed out — skipping audio mux.")
            if output.exists():
                output.unlink()
            video_only.rename(output)


# ======================================================================
# --- FILE: main.py ---
# ======================================================================

"""
main.py — CLI Entry Point for Face Blur Pipeline
==================================================

Supports the following commands:

    # Process a single video
    python main.py --video sample_inputs/sample_video.mp4

    # Process a single image
    python main.py --image sample_inputs/sample_image.jpg

    # Batch-process a directory of images
    python main.py --input-dir datasets/images/

    # Batch-process a directory of videos
    python main.py --input-dir datasets/videos/ --type video

    # Use pixelation instead of Gaussian blur
    python main.py --video sample_inputs/sample_video.mp4 --mode pixelate

    # Enable debug output (detection boxes, tracker IDs)
    python main.py --video sample_inputs/sample_video.mp4 --debug

    # Set custom confidence threshold
    python main.py --image sample_inputs/sample_image.jpg --confidence 0.5

All outputs are saved to  outputs/blurred_videos/  or  outputs/blurred_images/.
Debug visualisations go to  outputs/debug/.
"""

import argparse
import logging
import sys
from pathlib import Path

# Ensure the project root is on sys.path so 'app' is importable
PROJECT_ROOT = Path(__file__).resolve().parent

# NOTE: app.* imports are deferred into main() so that `--help`
# works even before dependencies are installed via pip.


def parse_args() -> argparse.Namespace:
    """Build and parse CLI arguments."""
    parser = argparse.ArgumentParser(
        prog="face_blur",
        description=(
            "Face Blur on Surveillance Videos & Images\n"
            "==========================================\n"
            "Detects and anonymises every visible human face in videos\n"
            "and images using deep-learning-based detection (RetinaFace)\n"
            "and multi-object tracking (ByteTrack)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # ── Input sources (mutually exclusive: --video, --image, --input-dir)
    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument(
        "--video",
        type=str,
        help="Path to a single video file (MP4, AVI, MKV, MOV).",
    )
    input_group.add_argument(
        "--image",
        type=str,
        help="Path to a single image file (JPG, PNG, BMP, etc.).",
    )
    input_group.add_argument(
        "--input-dir",
        type=str,
        help="Path to a directory of images or videos for batch processing.",
    )

    # ── Processing options
    parser.add_argument(
        "--mode",
        type=str,
        choices=["gaussian", "pixelate"],
        default="gaussian",
        help="Blur mode: 'gaussian' (default) or 'pixelate'.",
    )
    parser.add_argument(
        "--confidence",
        type=float,
        default=None,
        help="Override minimum confidence threshold for HIGH-tier detections (default: 0.8).",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Custom output directory (overrides default output paths).",
    )
    parser.add_argument(
        "--type",
        type=str,
        choices=["image", "video"],
        default="image",
        help="Content type when using --input-dir (default: image).",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug output (detection boxes, tracker IDs, confidence scores).",
    )

    return parser.parse_args()


def main() -> None:
    """Main entry point."""
    args = parse_args()

    # ── Deferred imports (so --help works without deps) ───────────────

    # ── Setup logging ─────────────────────────────────────────────────
    logger = setup_logging(level=logging.DEBUG if args.debug else logging.INFO)
    logger.info("=" * 60)
    logger.info("  Face Blur Pipeline — Starting")
    logger.info("=" * 60)

    # ── Apply CLI overrides to config ─────────────────────────────────
    # We mutate the global singleton config so all modules pick up changes.
    cfg.blur_mode = args.mode
    cfg.debug = args.debug

    if args.confidence is not None:
        cfg.confidence_high = args.confidence
        logger.info("Confidence threshold overridden to %.2f", args.confidence)

    logger.info("Blur mode : %s", cfg.blur_mode)
    logger.info("Device    : %s", cfg.device)
    logger.info("Debug     : %s", cfg.debug)

    ensure_dirs()

    # ── Route to the appropriate processor ────────────────────────────

    if args.video:
        # Single video processing
        processor = VideoProcessor(cfg)
        result = processor.process_video(args.video, args.output_dir)
        if result:
            logger.info("✓ Output saved to: %s", result)
        else:
            logger.error("✗ Video processing failed.")
            sys.exit(1)

    elif args.image:
        # Single image processing
        processor = ImageProcessor(cfg)
        result = processor.process_image(args.image, args.output_dir)
        if result:
            logger.info("✓ Output saved to: %s", result)
        else:
            logger.error("✗ Image processing failed.")
            sys.exit(1)

    elif args.input_dir:
        # Batch processing
        if args.type == "video":
            processor = VideoProcessor(cfg)
            results = processor.process_directory(args.input_dir, args.output_dir)
        else:
            processor = ImageProcessor(cfg)
            results = processor.process_directory(args.input_dir, args.output_dir)

        logger.info("✓ Batch complete: %d outputs generated.", len(results))

    logger.info("=" * 60)
    logger.info("  Face Blur Pipeline — Done")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
